---
# - include_role:
#     name: microk8s

# - include_role:
#     name: sonarqube

# Ensure uniqueness be adding unique host_group
# - set_fact:
#     github_repo_name: "{{ extra_vars.github_repo_prefix }}-{{ host_group }}"

# - include_role:
#     name: github
#     tasks_from: ensure-repo

# - include_role:
#     name: github
#     tasks_from: ensure-repo-secret
#   vars:
#     github_secret_key: "{{ item.key }}"
#     github_secret_value: "{{ item.value }}"
#   loop:
#     - { key: 'DT_TENANT_URL', value: '{{ dynatrace_tenant_url }}' }
#     - { key: 'DT_API_TOKEN', value: '{{ dynatrace_api_token }}' }
#     - { key: 'INGRESS_PROTOCOL', value: '{{ ingress_protocol }}' }
#     - { key: 'INGRESS_DOMAIN', value: '{{ ingress_domain }}' }
#     - { key: 'KEPTN_API_TOKEN', value: '{{ ca_api_token | default(None) }}' }
#     - { key: 'KEPTN_ENDPOINT', value: '{{ ca_endpoint | default(None) | replace("/api","") }}' }
    # - { key: 'KUBECONFIG_FILE', value: '' }

# Include use case specific Dashboard values
- set_fact:
    include_dashboard_value_file: "{{ role_path }}/templates/sonarqube-dashboard.yml.j2"

- include_role:
    name: dashboard
    tasks_from: template-values-file

- include_role:
    name: dashboard
