name: Quality Gates

on:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_B64 }}
        with:
          args: get ns
  deploy:
    runs-on: ubuntu-latest
    container: dtzar/helm-kubectl
    needs: verify
    steps:
      - uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'config'
          fileDir: '/github/home/.kube/'
          encodedString: ${{ secrets.KUBECONFIG_B64 }}
      - env:
          INGRESS_PROTOCOL: ${{ secrets.INGRESS_PROTOCOL }}
          INGRESS_DOMAIN: ${{ secrets.INGRESS_DOMAIN }}
        run: >
          helm list -A
  init-cloudautomation:
    runs-on: ubuntu-latest
    needs: deploy
    container:
      image: dynatraceace/keptn-gitlab-runner:2.2
      env:
        KEPTN_ENDPOINT: ${{ secrets.KEPTN_ENDPOINT }}
        KEPTN_API_TOKEN: ${{ secrets.KEPTN_API_TOKEN }}
        KEPTN_PROJECT: simplenode-github
        KEPTN_SERVICE: simplenodeservice
        KEPTN_STAGE: staging
        KEPTN_SOURCE: github
        SHIPYARD_FILE: cloudautomation/shipyard.yaml
        SLO_FILE: cloudautomation/slo.yaml
        SLI_FILE: cloudautomation/sli.yaml
        DT_CONFIG_FILE: cloudautomation/dynatrace.conf.yaml
    steps:
      - uses: actions/checkout@v3
      - name: Init CA project and services
        run: /keptn/keptn_init.sh
