---
- name: Get Github public encryption key
  block:
  - uri:
      url: "https://api.github.com/repos/{{ extra_vars.github_org }}/{{ github_repo_name }}/actions/secrets/public-key"
      method: GET
      status_code: [200]
      return_content: yes
      headers:
        Accept: "application/vnd.github+json"
        Authorization: "Bearer {{ extra_vars.github_token }}"
    register: github_public_key_raw
  - set_fact:
      github_encryption_key: "{{ github_public_key_raw.json.key }}"
      github_encryption_key_id: "{{ github_public_key_raw.json.key_id }}"
  when: github_encryption_key is not defined or github_encryption_key_id is not defined

- name: Encrypt value
  script: encrypt-value.py {{ github_encryption_key }} {{ github_secret_value }}
  args:
    executable: python3
  register: encrypt_secret_value_raw

- name: Create secret
  uri:
    url: "https://api.github.com/repos/{{ extra_vars.github_org }}/{{ github_repo_name }}/actions/secrets/{{ github_secret_key }}"
    method: PUT
    status_code: [201, 204]
    return_content: yes
    headers:
      Accept: "application/vnd.github+json"
      Authorization: "Bearer {{ extra_vars.github_token }}"
    body_format: json
    body:
      encrypted_value: "{{ encrypt_secret_value_raw.stdout }}"
      key_id: "{{ github_encryption_key_id }}"
  register: github_put_secret_raw
